namespace EmbreeSharp.Native;

public enum RTCSubdivisionMode : int
{
    RTC_SUBDIVISION_MODE_NO_BOUNDARY = 0,
    RTC_SUBDIVISION_MODE_SMOOTH_BOUNDARY = 1,
    RTC_SUBDIVISION_MODE_PIN_CORNERS = 2,
    RTC_SUBDIVISION_MODE_PIN_BOUNDARY = 3,
    RTC_SUBDIVISION_MODE_PIN_ALL = 4,
}
