name: 'Publish native library'

on:
  workflow_dispatch:

jobs:
  build:
    name: Build EmbreeSharp
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: run nuget package script
      run: |
        cd Scripts
        ./pack-native.ps1
        cd ../
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "./Script/build" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{secrets.NUGET_APIKEY}}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
