name: 'Test'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NuGetDirectory: ${{github.workspace}}/nuget
  DownloadName: embree_native
  EmbreeVersion: 4.0.1

jobs:
  test-win-x64:
    name: Test EmbreeSharp on win-x64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download official release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "embree/embree"
        tag: "v${{env.EmbreeVersion}}"
        fileName: "embree-${{env.EmbreeVersion}}.x64.windows.zip"
        out-file-path: ${{env.DownloadName}}
    - name: Unzip embree win-x64
      run: 7z x ${{github.workspace}}/${{env.DownloadName}}/embree-${{env.EmbreeVersion}}.x64.windows.zip -o${{github.workspace}} -aoa
    - name: Copy native lib
      run: |
          Copy-Item ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x64.windows/bin/embree4.dll -Destination ${{github.workspace}}/EmbreeSharp/runtimes/win-x64/native/
          Copy-Item ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x64.windows/bin/tbb12.dll -Destination ${{github.workspace}}/EmbreeSharp/runtimes/win-x64/native/
          Copy-Item ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x64.windows/bin/tbbmalloc.dll -Destination ${{github.workspace}}/EmbreeSharp/runtimes/win-x64/native/
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore

  test-linux-x64:
    name: Test EmbreeSharp on linux-x64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download official release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "embree/embree"
        tag: "v${{env.EmbreeVersion}}"
        fileName: "embree-${{env.EmbreeVersion}}.x86_64.linux.tar.gz"
        out-file-path: ${{env.DownloadName}}
    - name: Unzip embree linux-x64
      run: tar -zxvf ${{github.workspace}}/${{env.DownloadName}}/embree-${{env.EmbreeVersion}}.x86_64.linux.tar.gz -C ${{github.workspace}}
    - name: Copy native lib
      run: |
          cp -a ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x86_64.linux/lib/libembree4.so.4 ${{github.workspace}}/EmbreeSharp/runtimes/linux-x64/native/libembree4.so
          cp -a ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x86_64.linux/lib/libtbb.so.12.7 ${{github.workspace}}/EmbreeSharp/runtimes/linux-x64/native/libtbb.so
          cp -a ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x86_64.linux/lib/libtbbmalloc.so.2.7 ${{github.workspace}}/EmbreeSharp/runtimes/linux-x64/native/libtbbmalloc.so
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore

  test-osx-x64:
    name: Test EmbreeSharp on osx-x64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download official release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "embree/embree"
        tag: "v${{env.EmbreeVersion}}"
        fileName: "embree-${{env.EmbreeVersion}}.x86_64.macosx.zip"
        out-file-path: ${{env.DownloadName}}
    - name: Unzip embree osx-x64
      run: unzip -o ${{github.workspace}}/${{env.DownloadName}}/embree-${{env.EmbreeVersion}}.x86_64.macosx.zip -d ${{github.workspace}}
    - name: Copy native lib
      run: |
          cp -a ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x86_64.macosx/lib/libembree4.4.dylib ${{github.workspace}}/EmbreeSharp/runtimes/osx-x64/native/libembree4.dylib
          cp -a ${{github.workspace}}/embree-${{env.EmbreeVersion}}.x86_64.macosx/lib/libtbb.12.7.dylib ${{github.workspace}}/EmbreeSharp/runtimes/osx-x64/native/libtbb.dylib
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore
